//! Per-model metrics aggregation for the agent layer.
//!
//! `ModelUsage` aggregates token counts and cost across many requests
//! against the same model. The per-request shape comes from `ir::Usage`;
//! this is the rolled-up view that surfaces in `AgentMetrics`.

#![allow(missing_docs)]

use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

/// Per-model usage statistics tracking.
///
/// Tracks API usage for each model separately, enabling accurate cost
/// attribution when multiple models are used (e.g., Haiku for tool
/// summarization, Opus for the main agent).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModelUsage {
    /// Input tokens consumed by this model.
    pub input_tokens: u64,
    /// Output tokens generated by this model.
    pub output_tokens: u64,
    /// Cache read tokens.
    #[serde(default)]
    pub cache_read_input_tokens: u64,
    /// Cache creation tokens.
    #[serde(default)]
    pub cache_creation_input_tokens: u64,
    /// Number of server-side web search requests attributed to this model.
    #[serde(default)]
    pub web_search_requests: u64,
    /// Number of server-side web fetch requests attributed to this model.
    #[serde(default)]
    pub web_fetch_requests: u64,
    /// Estimated cost in USD for this model's usage.
    #[serde(default)]
    pub cost_usd: Decimal,
    /// Context window size for this model.
    #[serde(default)]
    pub context_window: u64,
}

impl ModelUsage {
    /// Build a snapshot from a single IR usage record + model id.
    pub fn from_ir(usage: &crate::ir::Usage, model: &str) -> Self {
        let cost = crate::budget::pricing::global_pricing_table().calculate(model, usage);
        let context_window = crate::models::context_window::for_model(model);
        let (web_search, web_fetch) = usage
            .server_tool_invocations
            .as_ref()
            .map(|s| (s.web_search.unwrap_or(0), s.web_fetch.unwrap_or(0)))
            .unwrap_or((0, 0));
        Self {
            input_tokens: usage.input_tokens,
            output_tokens: usage.output_tokens,
            cache_read_input_tokens: usage.cached_input_tokens.unwrap_or(0),
            cache_creation_input_tokens: usage.cache_creation_tokens.unwrap_or(0),
            web_search_requests: web_search,
            web_fetch_requests: web_fetch,
            cost_usd: cost,
            context_window,
        }
    }

    /// Merge another `ModelUsage` snapshot into self.
    pub fn add(&mut self, other: &ModelUsage) {
        self.input_tokens = self.input_tokens.saturating_add(other.input_tokens);
        self.output_tokens = self.output_tokens.saturating_add(other.output_tokens);
        self.cache_read_input_tokens = self
            .cache_read_input_tokens
            .saturating_add(other.cache_read_input_tokens);
        self.cache_creation_input_tokens = self
            .cache_creation_input_tokens
            .saturating_add(other.cache_creation_input_tokens);
        self.web_search_requests = self
            .web_search_requests
            .saturating_add(other.web_search_requests);
        self.web_fetch_requests = self
            .web_fetch_requests
            .saturating_add(other.web_fetch_requests);
        self.cost_usd += other.cost_usd;
    }

    /// Fold a single IR usage record into the running totals.
    pub fn add_ir_usage(&mut self, usage: &crate::ir::Usage, model: &str) {
        self.input_tokens = self.input_tokens.saturating_add(usage.input_tokens);
        self.output_tokens = self.output_tokens.saturating_add(usage.output_tokens);
        self.cache_read_input_tokens = self
            .cache_read_input_tokens
            .saturating_add(usage.cached_input_tokens.unwrap_or(0));
        self.cache_creation_input_tokens = self
            .cache_creation_input_tokens
            .saturating_add(usage.cache_creation_tokens.unwrap_or(0));
        self.cost_usd += crate::budget::pricing::global_pricing_table().calculate(model, usage);
        if let Some(ref invocations) = usage.server_tool_invocations {
            if let Some(ws) = invocations.web_search {
                self.web_search_requests = self.web_search_requests.saturating_add(ws);
            }
            if let Some(wf) = invocations.web_fetch {
                self.web_fetch_requests = self.web_fetch_requests.saturating_add(wf);
            }
        }
    }

    pub fn total_tokens(&self) -> u64 {
        self.input_tokens + self.output_tokens
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_ir_populates_fields() {
        let usage = crate::ir::Usage {
            input_tokens: 1000,
            output_tokens: 500,
            cached_input_tokens: Some(100),
            cache_creation_tokens: Some(50),
            ..Default::default()
        };
        let mu = ModelUsage::from_ir(&usage, "claude-sonnet-4-5");
        assert_eq!(mu.input_tokens, 1000);
        assert_eq!(mu.output_tokens, 500);
        assert_eq!(mu.cache_read_input_tokens, 100);
        assert_eq!(mu.cache_creation_input_tokens, 50);
        assert!(mu.cost_usd > Decimal::ZERO);
    }

    #[test]
    fn add_aggregates() {
        let mut a = ModelUsage {
            input_tokens: 100,
            output_tokens: 50,
            cost_usd: rust_decimal_macros::dec!(0.01),
            ..Default::default()
        };
        let b = ModelUsage {
            input_tokens: 200,
            output_tokens: 100,
            cost_usd: rust_decimal_macros::dec!(0.02),
            ..Default::default()
        };
        a.add(&b);
        assert_eq!(a.input_tokens, 300);
        assert_eq!(a.output_tokens, 150);
        assert_eq!(a.cost_usd, rust_decimal_macros::dec!(0.03));
    }
}
